system:
  debug: 
    log_level: debug

ai:
  provider: "openai" # "openai" or "vertexai"

  openai:
    model: "gpt-3.5-turbo" # Check the list of available models by `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`

  vertexai:
    project: "gen-ai-lab-391309"
    location: "us-central1"
    model: "gemini-1.5-flash-001"
  
  commands:
    - describe:
        description: "Generate a detailed description of the Issue."
        system_prompt: "以下は GitHub の問題とそれに対するコメントです。詳細な説明を日本語で作成してください。\n"
    - suggest:
        description: "Provide suggestions for improvement based on the contents of the Issue."
        system_prompt: "以下は GitHub の問題とそれに対するコメントです。課題の内容から解決すべき課題を特定し、改善案を日本語で 3 つ挙げてください。\n"
    - ask:
        description: "Answer free-text questions."
        system_prompt: "以下は GitHub の問題とそれに対するコメントです。内容に基づいて、次の質問に対する詳細な回答を日本語で提供してください。\n"
